name: run-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: checkout prebuilt binary
      run: ./script/checkout_prebuilt_binary_for_ci.sh ${{ secrets.RAFI_PREBUILT_BINARY_USER }} ${{ secrets.RAFI_PREBUILT_BINARY_ACCESS_TOKEN }}
    - name: check revision
      run: (cd third_party/rafi-prebuilt-binary; git log -1)
    # Workaround for a bug of GitHub Actions
    #   - https://github.com/actions/virtual-environments/issues/83
    #   - https://github.com/actions/virtual-environments/issues/110
    - name: install additional packages
      run: >
        sudo apt-get install -y ninja-build
    - name: build_gtest
      run: ./script/build_gtest.sh
    - name: build_release
      run: ./script/build_release.sh
    - name: run rafi-emu unit test
      run: ./script/run_emu_test.sh Release
    - name: run riscv-tests on rafi-emu
      run: ./script/run_emu_riscv_tests.sh
    - name: run linux on emu
      run: ./script/run_emu_linux.sh
    - name: run rafi-sim unit test (SystemVerilog verification by verilator)
      run: ./script/run_vtest.sh Release
    - name: run riscv-tests on rafi-sim
      run: ./script/run_sim_riscv_tests.sh
