name: run-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: checkout prebuilt binary
      run: ./script/checkout_prebuilt_binary_for_ci.sh ${{ secrets.RAFI_PREBUILT_BINARY_USER }} ${{ secrets.RAFI_PREBUILT_BINARY_ACCESS_TOKEN }}
    - name: check revision
      run: (cd third_party/rafi-prebuilt-binary; git log -1)
    # Workaround for a bug of GitHub Actions
    #   - https://github.com/actions/virtual-environments/issues/83
    #   - https://github.com/actions/virtual-environments/issues/110
    - name: install additional packages
      run: >
        sudo apt-get install -y ninja-build libboost-filesystem1.65.1 libboost-program-options1.65.1 libboost1.65-dev
        && sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
        && sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.65.1 /usr/lib/x86_64-linux-gnu/libboost_program_options.so
    - name: build_gtest
      run: ./script/build_gtest.sh
    - name: build_release
      run: ./script/build_release.sh
    - name: run rafi-emu-test
      run: ./script/run_emu_test.sh Release
    - name: run riscv-tests on emu
      run: ./script/run_emu_riscv_tests.sh
    - name: run linux on emu
      run: ./script/run_emu_linux.sh
    - name: run verilator test
      run: ./script/run_vtest.sh Release
