name: run-verilator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: checkout prebuilt binary
      run: ./script/checkout_prebuilt_binary_for_ci.sh ${{ secrets.RAFI_PREBUILT_BINARY_USER }} ${{ secrets.RAFI_PREBUILT_BINARY_ACCESS_TOKEN }}
    # Workaround for a bug of GitHub Actions
    #   - https://github.com/actions/virtual-environments/issues/83
    #   - https://github.com/actions/virtual-environments/issues/110
    - name: build verilator
      run: ./script/build_verilator.sh
    - name: run verilator
      run: ./script/run_verilator.sh
